### PR TITLE
Issue with multiple solvers

### LINKED ISSUE #362: Multiple solvers cause compiling issue on ubuntu (works fine on mac)
**Describe the bug**

I am generating 2 solvers and when i try to build my cargo project including both I get this type of error:

```
auto_preconditioning_functions.c:(.text.auto_preconditioning_functions_fmin+0x0): multiple definition of auto_preconditioning_functions_fmin'; /home/gello/control-rs/target/arm-unknown-linux-gnueabihf/release/deps/libicasadi_ik_right-18d9e096eb38edbe.rlib(cd802d741d7fdd7c-auto_preconditioning_functions.o):auto_preconditioning_functions.c:(.text.auto_preconditioning_functions_fmin+0x0): first defined here
```

It seems to only happen for preconditioning functions having the same name.

**To Reproduce**

This is how i am generating the solvers
```
problem = og.builder.Problem(u, p, cost).with_constraints(bounds)
    build_config = og.config.BuildConfiguration() \
        .with_build_directory("solvers_left") \
        .with_build_mode("release") \
        .with_rebuild(True) \
        .with_build_c_bindings() \
        # .with_target_system("rpi")         <-- i tried both with and without this
    meta = og.config.OptimizerMeta() \
        .with_optimizer_name(f"ik_{side}")
    solver_config = og.config.SolverConfiguration() \
        .with_tolerance(1e-7) \
        .with_preconditioning(False)
    builder = og.builder.OpEnOptimizerBuilder(problem,
                                            meta,
                                            build_config,
                                            solver_config)\
                                            .with_generate_not_build_flag(False).with_verbosity_level(0)
```

**System information:**

This issue only occurs on Ubuntu. It happens both on a raspberry pi and on an Orin but it works fine on my mac.

This is `rustup show` for the Orin
```
Default host: aarch64-unknown-linux-gnu 
rustup home:  /home/orin/.rustup
stable-aarch64-unknown-linux-gnu (default)
rustc 1.79.0 (129f3b996 2024-06-10)
```

And this is for Mac
```
Default host: aarch64-apple-darwin
rustup home:  /Users/seif/.rustup
installed toolchains
--------------------
stable-aarch64-apple-darwin
1.80.1-aarch64-apple-darwin (default)
active toolchain
----------------
1.80.1-aarch64-apple-darwin (default)
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

I tried both 1.79 and 1.80 rust versions and it still doesn't work.

I also followed what was suggested in #151 but it didn't help

### PR DESCRIPTION
**Pull request by alphaville**
## Main Changes

- Making some casadi-generated functions `static` (e.g., `casadi_sq` and `casadi_fmin`)

## Associated Issues

- Closes #362

## TODOs

- [x] Documentation 
- [x] All tests must pass
- [x] Update `CHANGELOG`(s)
- [x] ~Update webpage documentation~
- [x] Bump versions (in `CHANGELOG`, `Cargo.toml` and `VERSION`)

### CODE REVIEW

**Comment by wrseif** [comment]
it seems to work with these changes. however the only functions that i needed to make static are `casadi_fabs, casadi_fmax, casadi_sq, casadi_fmin` but i noticed you also added `casadi_hypot, casadi_sign`.

is it possible there's additional functions that may cause issues depending on the casadi functions used?

**Comment by alphaville** [comment]
> is it possible there's additional functions that may cause issues depending on the casadi functions used?

I'll double-check

**Comment by alphaville** [comment]
@wrseif I've looked into the [code generator](https://github.com/casadi/casadi/blob/main/casadi/core/code_generator.cpp) of CasADi and it seems that the functions to take into account are:

```python
fncs_list = ["casadi_sq", "casadi_fmax",
    "casadi_fmin", "casadi_hypot", "casadi_sign",
    "casadi_log1p", "casadi_expm1"]
```

**Review by ruairimoran — APPROVED** [review]
lgtm

**Pull request merged**
