### PR TITLE
TCP server: better error handling

### PR DESCRIPTION
**Pull request by alphaville**
Addressing issue #61

TODOs:

- [x] Fix malformed JSON
- [x] Improve error reporting (return informative message); currently, only an error code is returned
- [x] Write tests in Python
- [x] Update docs
- [x] Update CHANGELOG

### CODE REVIEW

**Comment by korken89** [comment]
We should also look into providing the starting guess of the decision variables, but that is probably for another PR :)

**Comment by alphaville** [comment]
@korken89 You can provide the initial guess as follows:

```json
{
    "Run":
        {
            "parameter": [1.0, 2.0],
            "initial_guess": [5.0, 6.0]
        }
}
```

**Comment by korken89** [comment]
I mean in the python tcp interface :)

**Comment by alphaville** [comment]
@korken89 It's supported in the Python interface too. Having constructed an instance of `OptimizerTcpManager`, use `call` with two arguments. The first argument is the parameter and the second (optional) argument is the initial guess. For example:

```python
mng = og.tcp.OptimizerTcpManager('python_test_build/tcp_enabled_optimizer')
mng.start()
solution = mng.call([1.0, 50.0, 100.0], [0.0, 1.0])
# or...
solution = mng.call([1.0, 50.0, 100.0], initial_guess=[0.0, 1.0])
```

**Comment by alphaville** [comment]
@korken89 I don't know happened, but without changing anything, Travis fails all tests with Python versions <3.6 - see for example [this log](https://travis-ci.org/alphaville/optimization-engine/jobs/559458102). There, throughout lines 1012-1030, we see that travis fails to install numpy and gives the error

```
RuntimeError: Python version >= 3.5 required.
```

I would be OK with removing all support for Python 2.7 (soon to [retire](https://pythonclock.org/)), but neither version 3.4 works. 

I tried to do the same locally with Python 3.4 (using virtualenv) and I reproduced the error.

**Comment by korken89** [comment]
Oh, I'd remove it from the CI as you have done now

**Comment by alphaville** [comment]
@korken89 I added a clarification in the docs that Python >= 3.5 is required. You need to approve this if you agree with these changes so that I can merge it in `master`.

**Pull request merged**
