### PR TITLE
Move to edition 2018, cleanup, and simplified user interface and imports

### LINKED ISSUE #9: Examples
We need to add examples in the standard Rust `examples` directory.

### PR DESCRIPTION
**Pull request by korken89**
A lot of updates, have a look if something is missing. See changelog and commit history for all the updates :)

Closes #9 #10 #11

### CODE REVIEW

**Comment by alphaville** [comment]
@korken89 Hi Emil. Wow! That's a lot of work! I'll have a look at it tomorrow.

**Comment by korken89** [comment]
Awesome and thanks! 

Most of it is refactoring and some clean up (I really like this part of rust) so I think the code is more readable now :) 
The main changes are then listed in the CHANGELOG, nothing big, mostly simplifications for the user.

I will now go to the C/C++ lib generation.

**Comment by korken89** [comment]
Hi Pantelis, can we merge this soon? 
I'd like to finalize the C/C++ libs which are dependent on this part :)

**Comment by alphaville** [comment]
> Hi Pantelis, can we merge this soon?
> I'd like to finalize the C/C++ libs which are dependent on this part :)

Hi Emil. Sure, just let me check this tomorrow. I didn't have time over this weekend. Will that be OK?

**Comment by korken89** [comment]
Yeah no problem!
If you have questions we can talk on Skype :)

**Comment by alphaville** [comment]
@korken89 Emil, these changes look nice, but it doesn't work on my machine. I'll create an issue so that you can have a look.

**Pull request merged**
