### PR TITLE
Fix/42: documentation on rust code

### LINKED ISSUE #42: Documentation of OpEn v0.4.0 on website is stale
The documentation at https://alphaville.github.io/optimization-engine/docs/openrust is stale and needs to be updated.

### PR DESCRIPTION
**Pull request by alphaville**
In this pull request:

- Updated documentation of the Rust code
- Documentation for the homotopy method in Rust
- Mild restructuring of docs (reordered sections in sidebar)
- Documentation for Python-to-Rust interface over TCP
- Python examples: nonlinear estimation
- Added Rust example in `examples`
- Added figure files for the newly introduced examples

Side note: The new nonlinear state estimation is solved in around 3ms in OpEn and in 73s (seconds!) in fmincon (I tried it in MATLAB first).

Closes #42.

### CODE REVIEW

**Comment by alphaville** [comment]
Update: I added an example on nonlinear state estimation. I haven't updated the online website yet. To run it locally run `yarn start` from within `website/`.

From the example:

python_estimation

**Comment by korken89** [comment]
Awesome, I'll have a look today!

**Comment by alphaville** [comment]
@korken89 This PR is ready to be merged from my side.

**Comment by alphaville** [comment]
@korken89 No objections. Let's merge it. I think we should update the website too. What do you think?

**Comment by korken89** [comment]
Let's update the site with the next release to have it all synced :) We are close to the next release

**Pull request merged**
