### PR TITLE
Add ARM MacOS support for Python Bindings

### LINKED ISSUE #350: Python direct interface fails on ARM-based MacOS platforms
**Describe the bug**

The direct interface fails on ARM-based MacOS platforms due to a linking error. 

The TCP interface still works as expected and can be used as a workaround, but this isn't ideal.

**To Reproduce**

1. Try to build with Python bindings.

```python
 @staticmethod
    def build_solver(output, parameters, cost, constraints, name):
        problem = og.opengen.builder \
            .Problem(output, parameters, cost) \
            .with_constraints(constraints)
        build_config = og.opengen.config.BuildConfiguration() \
            .with_build_directory(BUILD_DIR) \
            .with_build_mode('debug') \
            .with_build_python_bindings()
        meta = og.opengen.config.OptimizerMeta() \
            .with_optimizer_name(name)
        solver_config = og.opengen.config.SolverConfiguration() \
            .with_tolerance(1e-03) \
            .with_initial_tolerance(1e-03)
        builder = og.opengen.builder.OpEnOptimizerBuilder(
            problem,
            meta,
            build_config,
            solver_config
        )
        # This line fails with linking errors for all items which should be accessible
        builder.build()
        # This isn't reached
        sys.path.insert(1, f"{BUILD_DIR}/{name}")
        return importlib.import_module(name).solver()
```

**Expected behavior**

Build succeeds, solver is returned from the function above.

**System information:**

:warning: Please, provide the following information:

 - System/Platform: Macbook Pro with M2 Max Processor
 - OS: MacOS
 - What is the output of `rustup show`? N/A
 - What is the output of `rustc -V`? N/A
 - Python/MATLAB version if relevant: Python 3.12

**Additional context**

I will provide a PR to fix this issue.

### LINKED ISSUE #352: Upgrade macos-11 to macos-12 in GA
Upgrade macos-11 to [macos-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) in GA

**Update:** We should better change it to `macos-latest`

### PR DESCRIPTION
**Pull request by Creelman**
## Main Changes

Updates the Python direct interface `.cargo/config` template file to work with ARM-based Macs.

Fix based on PyO3 docs [here](https://pyo3.rs/main/building-and-distribution#macos)

## Associated Issues

- Closes #350 
- Closes #352 

## TODOs

- [x] Documentation 
- [x] All tests must pass
- [x] Update `CHANGELOG`(s)
- [x] Update webpage documentation
- [x] Bump versions (in `CHANGELOG`, `Cargo.toml` and `VERSION`)

## Other

Tested on M2 Max Macbook Pro

### CODE REVIEW

**Comment by Creelman** [comment]
@alphaville AFAICT that MacOS job will never run - as part of this PR will I update the CI definition to use `macos-latest`?

Looks like macos-11 runner got [deactivated in June](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/). I'm surprised it doesn't give a proper error, seems to match the behaviour described [here](https://stackoverflow.com/questions/70959954/error-waiting-for-a-runner-to-pick-up-this-job-using-github-actions) when Ubuntu got updated a while back.

**Comment by alphaville** [comment]
> @alphaville AFAICT that MacOS job will never run - as part of this PR will I update the CI definition to use `macos-latest`? If it's preferable to stick to a constant version, `macos-14` is the latest version
> 
> Looks like macos-11 runner got [deactivated in June](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/). I'm surprised it doesn't give a proper error, seems to match the behaviour described [here](https://stackoverflow.com/questions/70959954/error-waiting-for-a-runner-to-pick-up-this-job-using-github-actions) when Ubuntu got updated a while back.

@Creelman yes, I realised and created an issue (see #352). Can you please change it to `macos-latest`?

**Comment by Creelman** [comment]
Should be ready to try a build again

**Comment by Creelman** [comment]
Had to make a few more changes to support the new MacOS runner

* Updated Python to version 3.12. Required because actions/setup-python [does not support](https://github.com/actions/setup-python/issues/906) versions of Python <3.11 on Darwin Macs (`macos-latest` runs on Darwin M1 processors). I picked 3.12 as it's the latest version, and has been stable for 8 months now.
* I updated the Python version for all of the CI workflows for consistency, including the docs and Ubuntu runners. 
* Updated actions/setup-python from v2 to v5 (latest) to support this
* Updated the CI script to use the new Python version, and manually install setuptools to fix an issue where `pkg_resources` [could not be found](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources)

IIUC the documentation failure is because I'm testing in a fork, and should succeed on a rerun of the CI pipeline here.

Apologies for adding quite a few commits for a relatively small change - I couldn't replicate the issue locally.

**Comment by alphaville** [comment]
@Creelman many thanks for all the good work! I'll merge this now and I'll create a new version afterwards.

**Review by alphaville — APPROVED** [review]

**Pull request merged**
